name: "Setup agent"
description: ""
runs:
  using: "composite"
  steps:
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ../Qt
        key: ${{ matrix.config.os }}-${{ matrix.config.arch }}-${{ matrix.config.qt_version }}-QtCache

    - name: Install Qt
      if: ${{ matrix.config.qt_arch }}
      uses: jurplel/install-qt-action@v3
      with:
        version: ${{ matrix.config.qt_version }}
        arch: ${{ matrix.config.qt_arch }}
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        modules: ${{ matrix.config.qt_modules }}
        archives: qtbase qtimageformats qtsvg qttools qttranslations icu

    - name: Set boost env vars
      shell: sh
      run: |
        echo "BOOST_ROOT=${{github.workspace}}/3rdparty/boost" >> $GITHUB_ENV
        echo "BOOST_URL=https://sourceforge.net/projects/boost/files/boost/1.86.0/boost_1_86_0.tar.bz2/download" >> $GITHUB_ENV

    - name: Restore Boost cache
      uses: actions/cache@v4
      id: cache-boost
      with:
        path: ${{env.BOOST_ROOT}}
        key: ${{env.BOOST_URL}}

    - name: Install Boost
      shell: bash
      run: |
        if echo ${{ steps.cache-boost.outputs.cache-hit }} | grep -c "true"
        then
          echo "Using boost from cache"
        else
          echo "Downloading boost"
          if [ "$OS" == "Windows_NT" ]; then
            # fix up paths to be forward slashes consistently
            BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
          fi
          mkdir -p $BOOST_ROOT
          curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
          cd $BOOST_ROOT && cp -r boost_*/* .
          rm -rf boost_*/* download.tar.bz2 download.tar
        fi
        


