name: "CI Build"

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'website/**'
      - BUILD.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - latest.json
      - .gitignore
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'website/**'
      - BUILD.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - README.md
      - latest.json
      - .gitignore
  workflow_dispatch:

jobs:
  SaveVersion:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/klogg-version

      - name: Save version 
        run: echo $KLOGG_VERSION > klogg_version.txt

      - uses: actions/upload-artifact@v3
        with:
          name: klogg_version
          path: 'klogg_version.txt'
          if-no-files-found: error

  Windows:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: windows
            os_version: 2022
            qt_version: 6.7.3
            qt_modules: qt5compat
            qt_arch: win64_msvc2019_64
            arch: x64
            ssl_arch: -x64
            cmake_opts:
            artifacts_id: windows-x64-qt6

          - os: windows
            os_version: 2022
            qt_version: 5.15.2
            qt_arch: win32_msvc2019
            arch: x86
            cmake_opts:
            artifacts_id: windows-x86-qt5

    runs-on: ${{ matrix.config.os }}-${{ matrix.config.os_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache openssl
        id: cache-openssl
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}\openssl-1.1
          key: OpensslCache-1-1-1w

      - name: Download openssl
        if: ${{ steps.cache-openssl.outputs.cache-hit != 'true' }} 
        run: |
          Invoke-WebRequest -Uri "https://www.firedaemon.com/download-firedaemon-openssl-1.1.1-zip" -OutFile openssl.zip
          7z x openssl.zip 

      - name: Set openssl paths
        shell: sh
        run: |
          echo "SSL_DIR=${{ github.workspace }}\openssl-1.1\${{ matrix.config.arch }}\bin" >> $GITHUB_ENV
          echo "SSL_ARCH=${{ matrix.config.ssl_arch }}" >> $GITHUB_ENV 

      - uses: ./.github/actions/agent-setup
      - uses: ./.github/actions/klogg-version
      - uses: ./.github/actions/prepare-workspace-env
      
      - name: Prepare dev cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.config.arch }}

      - uses: ./.github/actions/agent-build
      - uses: ./.github/actions/agent-run-tests
      - uses: ./.github/actions/agent-package-win
        with:
          s3-key-id: ${{ secrets.WIN_CS_KEY_ID }}
          s3-secret: ${{ secrets.WIN_CS_SECRET }}
          s3-bucket: ${{ secrets.WIN_CS_BUCKET }}
     
# Final upload of all packages
      - uses: actions/upload-artifact@v3
        with:
          name: packages-${{ matrix.config.artifacts_id }}
          path: '${{ env.KLOGG_BUILD_ROOT }}/packages/*'
          if-no-files-found: error
